# SPDX-FileCopyrightText: Copyright 2025 New Vector Ltd.
# SPDX-FileCopyrightText: Copyright 2025, 2026 Element Creations Ltd.
#
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Element-Commercial

name: Upload translation files to Localazy
on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-node

      - name: Upload translations to Localazy
        run: pnpm localazy upload -w "$LOCALAZY_WRITE_KEY"
        env:
          LOCALAZY_WRITE_KEY: ${{ secrets.LOCALAZY_WRITE_KEY }}
